# Change these first
owner: arillo # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Arillo
    url: https://www.arillo.net

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.arillo.de
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://assets.arillo.net/logo.svg
  name: "Arillo's uptimes"
  introTitle: "**Arillo's** status of client websites."
  introMessage: This is a status page which uses **real-time** data.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
